// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseView: typeof import('./src/components/BaseView.vue')['default']
    CircleProgress: typeof import('./src/components/CircleProgress.vue')['default']
    CloudInput: typeof import('./src/components/CloudInput.vue')['default']
    CloudPicker: typeof import('./src/components/CloudPicker.vue')['default']
    DateInput: typeof import('./src/components/DateInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCloudSelect: typeof import('./src/components/ElCloudSelect.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlowImg: typeof import('./src/components/GlowImg.vue')['default']
    IconParkLink: typeof import('./src/components/IconParkLink.vue')['default']
    LevelProgress: typeof import('./src/components/LevelProgress.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutDatePicker: typeof import('@nutui/nutui')['DatePicker']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutPicker: typeof import('@nutui/nutui')['Picker']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    OsDataComponent: typeof import('./src/components/OsDataComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
